name: Python Lint & Type Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle mypy

      - name: Run pycodestyle (PEP8)
        run: |
          pycodestyle . --max-line-length=100

      - name: Run mypy (Type Check)
        run: |
          mypy . --ignore-missing-imports --strict
